version: '3.3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: kr-testbed-api
      POSTGRES_DB: kr-testbed-api
    volumes:
      - './db:/var/lib/postgresql'
    ports:
      - '5433:5432'
    networks:
      - app-network

  kr-testbed-api:
    image: nrg/kr-testbed-api:0.1
    environment:
      DATABASE_URL: postgres://kr-testbed-api:toor@db/kr-testbed-api
      ENV: dev
      APP_BIND_ADDRESS: 0.0.0.0:8080
      ALLOWED_ORIGIN: http://127.0.0.1:4100
      WEB_APP_URL: http://127.0.0.1:4100
      APP_URL: http://127.0.0.1:8080
      SECRET_KEY: heyo
      STORAGE_PATH: /var/local/kr-testbed-api/storage
    restart: 'no'
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - './storage:/var/local/kr-testbed-api/storage'

networks:
  app-network:
    driver: bridge
